In [97]:
!python3 -m pip install ipfs-api==0.2.3 urllib3 IPFS-Toolkit subgrounds torch web3 python-dotenv --upgrade --break-system-packages

In [12]:
import ipfsApi

def write_to_ipfs(client, file_path):
    # Connect to the local IPFS node

    # Add a file to IPFS
    res = client.add(file_path)
    
    # Print the IPFS hash (CID) of the added file
    print(f"Added file to IPFS with CID: {res['Hash']}")

    return res['Hash']

In [13]:
client = ipfsApi.Client('127.0.0.1', 5001)
# client = ipfshttpclient.connect()

In [14]:
# client.id()

In [15]:
# client.version()

In [16]:
lst = [1, 77, 'lol']
h = client.add_pyobj(lst)
h

'QmVocnDjam1EUunBKVNQpX4RGftscxKYkUfC4RDL1uq5to'

In [8]:
client.add_json({"a": "b"})

'QmYfNcRcvvyPKmc1DoDkZsA7HnZnyMoeoADegEsimXaxSL'

In [9]:
client.get_json("QmYfNcRcvvyPKmc1DoDkZsA7HnZnyMoeoADegEsimXaxSL")

HTTPError: 405 Client Error: Method Not Allowed for url: http://127.0.0.1:5001/api/v0/cat?stream-channels=true&encoding=json&arg=QmYfNcRcvvyPKmc1DoDkZsA7HnZnyMoeoADegEsimXaxSL

In [92]:
import requests

In [93]:
r = requests.get("https://ipfs.io/ipfs/Qmdc4HtimQNcjUyQUp1FPQ8SQSMa54eqN1azUPUifX13jc")

In [94]:
r.content.decode()

'"test"\n'

In [17]:
import torch

model_fn = lambda: torch.nn.Sequential(
    torch.nn.Linear(4, 8),
    torch.nn.ReLU(),
    torch.nn.Linear(8, 4))

In [18]:
model = model_fn()
torch.save(model.state_dict(), "/Users/sergmiller/Downloads/test_state.pth")

In [87]:
import ipfs_api

N = 5
for i in range(N):
    model = model_fn()
    torch.save(model.state_dict(), "/Users/sergmiller/Downloads/test_state.pth")
    r = ipfs_api.http_client.add("/Users/sergmiller/Downloads/test_state.pth")
    print(r.as_json()["Hash"])

QmZG8N5mxLiNCzE8Vnvtcr7UXbSVMQnHw4oCauJzpRkPM6
QmZPLDcxYVxwTwpKU36xmmJ6kiFiVL5BqWjf6K5bWfLD8n
QmW3Tar6cPjufwkgAfZrfsRRWM7RJSqCxiRJNPfv6X54Uy
QmaufME9pY9m416Z5UW5XFMaNyykGLmJnoe78oFr86TFcP
QmZRLQqeazAjcu3PMdJstq2hN1vC8oMrEMBS3eGiHcnP5E


In [91]:
ipfs_hash = "QmZG8N5mxLiNCzE8Vnvtcr7UXbSVMQnHw4oCauJzpRkPM6"
ipfs_api.http_client.get(ipfs_hash, "data")
state_dict = torch.load("data/" + ipfs_hash)
state_dict

OrderedDict([('0.weight',
              tensor([[-0.0738,  0.0869,  0.3928, -0.3066],
                      [ 0.2424,  0.3876, -0.1660, -0.4336],
                      [ 0.1969, -0.4670,  0.3551,  0.0669],
                      [-0.3318,  0.2161, -0.0250, -0.1481],
                      [-0.4831,  0.2456,  0.3855, -0.1747],
                      [ 0.4800, -0.4479,  0.4367,  0.0232],
                      [ 0.2181,  0.3120,  0.1250,  0.3864],
                      [-0.2516, -0.0652,  0.0953, -0.1061]])),
             ('0.bias',
              tensor([-0.0860, -0.1118, -0.0499, -0.0563, -0.3263,  0.4066,  0.4809, -0.1290])),
             ('2.weight',
              tensor([[ 0.1098,  0.1189, -0.3490,  0.2884, -0.2645,  0.1749, -0.2509, -0.0190],
                      [-0.2114, -0.2610,  0.0658, -0.3206, -0.2349,  0.0206, -0.0151,  0.1680],
                      [-0.1545, -0.1870,  0.2346, -0.2231,  0.0326, -0.2143, -0.3130,  0.0949],
                      [-0.1196, -0.1716,  0.3493,  0.255

In [85]:
model.load_state_dict(torch.load(r.as_json()["Hash"]))

<All keys matched successfully>

In [46]:
model

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
)

In [56]:
from subgrounds import Subgrounds

sg = Subgrounds()

# Load the subgraph
sub = sg.load_subgraph(
    "http://localhost:8000/subgraphs/name/unstoppable-models")

/var/folders/t7/03tm_x3j5_g71h1nsvq1wv780000gq/T/ipykernel_58312/397916585.py:3: ResourceWarning: unclosed <socket.socket fd=91, family=30, type=1, proto=6, laddr=('::1', 49619, 0, 0), raddr=('::1', 8000, 0, 0)>
  sg = Subgrounds()


In [ ]:
sub.

In [199]:
states = sg.query_df(sub.Query.modelStates())

In [200]:
states["modelStates_deleted"]

0    False
1     True
2    False
Name: modelStates_deleted, dtype: bool

In [201]:
states

modelStates_id  \
0  QmW3Tar6cPjufwkgAfZrfsRRWM7RJSqCxiRJNPfv6X54Uy   
1  QmZG8N5mxLiNCzE8Vnvtcr7UXbSVMQnHw4oCauJzpRkPM6   
2  QmZPLDcxYVxwTwpKU36xmmJ6kiFiVL5BqWjf6K5bWfLD8n   

                                  modelStates_url  modelStates_submittedAt  \
0  QmW3Tar6cPjufwkgAfZrfsRRWM7RJSqCxiRJNPfv6X54Uy               1717288667   
1  QmZG8N5mxLiNCzE8Vnvtcr7UXbSVMQnHw4oCauJzpRkPM6               1717288665   
2  QmZPLDcxYVxwTwpKU36xmmJ6kiFiVL5BqWjf6K5bWfLD8n               1717288667   

   modelStates_suspectedAt                     modelStates_suspectedBy  \
0                      NaN                                        None   
1                      NaN                                        None   
2             1.717289e+09  0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266   

  modelStates_learningPeriod_id  modelStates_deleted  
0                           0x2                False  
1                           0x1                 True  
2                           0x2                False

In [64]:
states["modelStates_url"]

0    https://linktodatafoo1
1    https://linktodatafoo2
Name: modelStates_url, dtype: object

In [193]:
import web3_utils
from importlib import reload
reload(web3_utils)

<module 'web3_utils' from '/Users/sergmiller/Documents/my/eth-prague-2024/research/web3_utils.py'>

In [194]:
import json

In [195]:
h = "QmZRLQqeazAjcu3PMdJstq2hN1vC8oMrEMBS3eGiHcnP5E"

In [197]:
web3_utils.call_contract("applyToLearnPeriod", int(time.time()), 1000000000000000)

AttributeDict({'type': 2,
 'status': 1,
 'cumulativeGasUsed': 118283,
 'logs': [AttributeDict({'address': '0x1429859428C0aBc9C2C47C8Ee9FBaf82cFA0F20f',
   'topics': [HexBytes('0x88da22df40e594023efac666521a621f15c10cba4708e3bb26853d578fff25ef'),
    HexBytes('0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266')],
   'data': HexBytes('0x00000000000000000000000000000000000000000000000000000000665bbba100000000000000000000000000000000000000000000000000000000665bbccd00000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000002'),
   'blockHash': HexBytes('0x54e170f947ad1c65bfac4cdbc1619981d115a0dfc1396cd61fd4822c137f984d'),
   'blockNumber': 70,
   'blockTimestamp': '0x665bbba3',
   'transactionHash': HexBytes('0xd0802d01b23101b8fd4ecb77051691212e0d8d939a9d1612e12475b96d32b662'),
   'transactionIndex': 0,
   'logIndex': 0,
   'removed': False})],
 'logsBloom': HexBytes('0x0002000000000000000000000000000000000

In [198]:
web3_utils.call_contract("submitState", h)

AttributeDict({'type': 2,
 'status': 1,
 'cumulativeGasUsed': 175414,
 'logs': [AttributeDict({'address': '0x1429859428C0aBc9C2C47C8Ee9FBaf82cFA0F20f',
   'topics': [HexBytes('0x30639130eea58a82aa3b1c5767d739114b2b1cd3f752b4d7b8fb16de61d74fde'),
    HexBytes('0x0000000000000000000000000000000000000000000000000000000000000002')],
   'data': HexBytes('0x000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000665bbbac000000000000000000000000000000000000000000000000000000000000002e516d5a524c517165617a416a637533504d644a73747132684e317643386f4d72454d42533365476948636e503545000000000000000000000000000000000000'),
   'blockHash': HexBytes('0x3b1660ab398fe9ab51d6eddbccf64dd8f9701d1c1a2f29c5842b331cbe2da1a5'),
   'blockNumber': 71,
   'blockTimestamp': '0x665bbbac',
   'transactionHash': HexBytes('0x377ee3efa32e3b70f845f08d5aeaaa722214d45b32050c2a38d01dd0b3201c6e'),
   'transactionIndex': 0,
   'logIndex': 0,
   'removed': False})],

In [171]:
from web3 import Web3
from dotenv import load_dotenv
import os
import json

load_dotenv()

w3 = Web3(Web3.HTTPProvider('http://127.0.0.1:8545'))

In [172]:
pk = os.environ.get('PRIVATE_KEY')
acct = w3.eth.account.from_key(pk)

In [173]:
w3.is_connected()

True

In [174]:
contract_addr = os.environ.get('CONTRACT_ADDRESS')
contract_addr = "0x04C89607413713Ec9775E14b954286519d836FEf"
with open("../abi.json", "r") as f:
    abi = json.load(f)
contract = w3.eth.contract(address=contract_addr, abi=abi)

In [175]:
contract_addr

'0x04C89607413713Ec9775E14b954286519d836FEf'

In [176]:
acct.address

'0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'

In [177]:
w3.eth.get_transaction_count(acct.address)

74

In [183]:
import time
unsent_tx = contract.functions.applyToLearnPeriod(int(time.time())).build_transaction({
    "from": acct.address,
    "nonce": w3.eth.get_transaction_count(acct.address),
    'value': 1000000000000000
})

<Function submitState>

In [184]:
signed_tx = w3.eth.account.sign_transaction(unsent_tx, private_key=acct.key)
tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
w3.eth.wait_for_transaction_receipt(tx_hash)

AttributeDict({'type': 2,
 'status': 1,
 'cumulativeGasUsed': 118271,
 'logs': [AttributeDict({'address': '0x04C89607413713Ec9775E14b954286519d836FEf',
   'topics': [HexBytes('0x88da22df40e594023efac666521a621f15c10cba4708e3bb26853d578fff25ef'),
    HexBytes('0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266')],
   'data': HexBytes('0x00000000000000000000000000000000000000000000000000000000665bb9bf00000000000000000000000000000000000000000000000000000000665bbaeb00000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000002'),
   'blockHash': HexBytes('0x33de8855ebb386a32382be68d716d9c5958963cca42dc1666c20fb5eb73f60a8'),
   'blockNumber': 59,
   'blockTimestamp': '0x665bb9d2',
   'transactionHash': HexBytes('0xd99d625a2e11ab60f38e3587abd11239ae7d1d746dd6bedb2c0758bf3532f570'),
   'transactionIndex': 0,
   'logIndex': 0,
   'removed': False})],
 'logsBloom': HexBytes('0x0002000000000000000000000000004000000

In [188]:
import time
unsent_tx = contract.functions.submitState(h).build_transaction({
    "from": acct.address,
    "nonce": w3.eth.get_transaction_count(acct.address),
    'value': 0
})

In [189]:
signed_tx = w3.eth.account.sign_transaction(unsent_tx, private_key=acct.key)
tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)
w3.eth.wait_for_transaction_receipt(tx_hash)

AttributeDict({'type': 2,
 'status': 1,
 'cumulativeGasUsed': 158314,
 'logs': [AttributeDict({'address': '0x04C89607413713Ec9775E14b954286519d836FEf',
   'topics': [HexBytes('0x30639130eea58a82aa3b1c5767d739114b2b1cd3f752b4d7b8fb16de61d74fde'),
    HexBytes('0x0000000000000000000000000000000000000000000000000000000000000002')],
   'data': HexBytes('0x000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000665bba99000000000000000000000000000000000000000000000000000000000000002e516d5a524c517165617a416a637533504d644a73747132684e317643386f4d72454d42533365476948636e503545000000000000000000000000000000000000'),
   'blockHash': HexBytes('0xb6c3a1baada8a0ced03762cddbdac2419832c35e23316569df46129dec6b09df'),
   'blockNumber': 61,
   'blockTimestamp': '0x665bba99',
   'transactionHash': HexBytes('0x8820a017ca1ff9594cc39b3cb0828dd17827eaea99c69527074496e827f601db'),
   'transactionIndex': 0,
   'logIndex': 0,
   'removed': False})],